package com.readmates.contract

import com.readmates.auth.application.service.AuthSessionService
import com.readmates.support.ReadmatesMySqlIntegrationTestSupport
import jakarta.servlet.http.Cookie
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user
import org.springframework.test.context.jdbc.Sql
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.get
import tools.jackson.databind.JsonNode
import tools.jackson.databind.ObjectMapper
import java.nio.file.Paths
import java.util.UUID

/**
 * Contract tests that verify server MockMvc responses match the recursive JSON key shapes
 * defined in the frontend zod schema fixture files under
 * front/tests/unit/__fixtures__/zod-schemas/.
 *
 * Each fixture file is generated by `pnpm --dir front zod:export-fixtures` and represents
 * the expected key set of the corresponding zod-validated API response shape. If the server
 * adds or removes an object field without updating
 * the zod schema (and therefore the fixture), this test fails.
 */
@SpringBootTest(
    properties = [
        "spring.flyway.locations=classpath:db/mysql/migration,classpath:db/mysql/dev",
    ],
)
@AutoConfigureMockMvc
@Tag("integration")
class FrontendZodSchemaContractTest
    @Autowired
    constructor(
        private val mockMvc: MockMvc,
        private val objectMapper: ObjectMapper,
        private val authSessionService: AuthSessionService,
        private val jdbcTemplate: JdbcTemplate,
    ) : ReadmatesMySqlIntegrationTestSupport() {
        private val zodFixturesDir =
            Paths.get(
                System.getProperty("readmates.frontend.zod.fixtures.dir")
                    ?: error("System property 'readmates.frontend.zod.fixtures.dir' is not set"),
            )
        private val createdSessionTokenHashes = linkedSetOf<String>()

        // Seeded host session: session 1 (팩트풀니스), state=PUBLISHED, visibility=PUBLIC
        private val seededHostSessionId = "00000000-0000-0000-0000-000000000301"

        @AfterEach
        fun cleanupSessions() {
            if (createdSessionTokenHashes.isEmpty()) {
                return
            }

            val placeholders = createdSessionTokenHashes.joinToString(",") { "?" }
            jdbcTemplate.update(
                "delete from auth_sessions where session_token_hash in ($placeholders)",
                *createdSessionTokenHashes.toTypedArray(),
            )
            createdSessionTokenHashes.clear()
        }

        @Test
        fun `host session detail response matches zod schema fixture key set`() {
            val response =
                mockMvc
                    .get("/api/host/sessions/$seededHostSessionId") {
                        with(user("host@example.com"))
                    }.andExpect {
                        status { isOk() }
                    }.andReturn()
                    .response.contentAsString

            assertJsonShapeMatches(response, "host-session-detail.json")
        }

        @Test
        fun `host notification delivery list response matches zod schema fixture key set`() {
            val response =
                mockMvc
                    .get("/api/host/notifications/deliveries") {
                        with(user("host@example.com"))
                    }.andExpect {
                        status { isOk() }
                    }.andReturn()
                    .response.contentAsString

            assertJsonShapeMatches(response, "host-notification-delivery-list.json")
        }

        @Test
        fun `host invitation list response matches zod schema fixture key set`() {
            val response =
                mockMvc
                    .get("/api/host/invitations") {
                        with(user("host@example.com"))
                    }.andExpect {
                        status { isOk() }
                    }.andReturn()
                    .response.contentAsString

            assertJsonShapeMatches(response, "host-invitation-list.json")
        }

        @Test
        fun `admin analytics overview response matches zod schema fixture key set`() {
            val response =
                mockMvc
                    .get("/api/admin/analytics/overview?window=30d") {
                        cookie(sessionCookieForUser(OWNER_USER_ID))
                    }.andExpect {
                        status { isOk() }
                    }.andReturn()
                    .response.contentAsString

            assertJsonShapeMatches(response, "admin-analytics-overview.json")
        }

        @Test
        @Sql(
            statements = [
                CLEANUP_CONTRACT_CURRENT_SESSION_SQL,
                INSERT_CONTRACT_CURRENT_SESSION_SQL,
                INSERT_CONTRACT_CURRENT_SESSION_PARTICIPANTS_SQL,
                INSERT_CONTRACT_CURRENT_SESSION_QUESTION_SQL,
                INSERT_CONTRACT_CURRENT_SESSION_CHECKIN_SQL,
                INSERT_CONTRACT_CURRENT_SESSION_ONE_LINE_REVIEW_SQL,
                INSERT_CONTRACT_CURRENT_SESSION_MY_LONG_REVIEW_SQL,
                INSERT_CONTRACT_CURRENT_SESSION_BOARD_LONG_REVIEW_SQL,
            ],
            executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD,
        )
        @Sql(
            statements = [
                CLEANUP_CONTRACT_CURRENT_SESSION_SQL,
            ],
            executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD,
        )
        fun `current session response matches zod schema fixture key set`() {
            val response =
                mockMvc
                    .get("/api/sessions/current") {
                        cookie(sessionCookieForUser(MEMBER_USER_ID))
                    }.andExpect {
                        status { isOk() }
                    }.andReturn()
                    .response.contentAsString

            assertJsonShapeMatches(response, "current-session.json")
        }

        @Test
        fun `recursive shape helper detects nested object key drift`() {
            val actual = objectMapper.readTree("""{"outer":{"serverOnly":true}}""")
            val expected = objectMapper.readTree("""{"outer":{"fixtureOnly":true}}""")

            assertThatThrownBy {
                assertJsonShapeMatches(
                    actual = actual,
                    expected = expected,
                    path = "$",
                    fixtureFileName = "inline-fixture.json",
                )
            }.isInstanceOf(AssertionError::class.java)
                .hasMessageContaining("JSON object key set at '$.outer'")
                .hasMessageContaining("serverOnly")
                .hasMessageContaining("fixtureOnly")
        }

        @Test
        fun `recursive shape helper detects object node type drift`() {
            val actual = objectMapper.readTree("""{"outer":null}""")
            val expected = objectMapper.readTree("""{"outer":{"field":true}}""")

            assertThatThrownBy {
                assertJsonShapeMatches(
                    actual = actual,
                    expected = expected,
                    path = "$",
                    fixtureFileName = "inline-fixture.json",
                )
            }.isInstanceOf(AssertionError::class.java)
                .hasMessageContaining("JSON node at '$.outer'")
                .hasMessageContaining("must be an object")
        }

        @Test
        fun `recursive shape helper detects missing representative array elements`() {
            val actual = objectMapper.readTree("""{"items":[]}""")
            val expected = objectMapper.readTree("""{"items":[{"field":true}]}""")

            assertThatThrownBy {
                assertJsonShapeMatches(
                    actual = actual,
                    expected = expected,
                    path = "$",
                    fixtureFileName = "inline-fixture.json",
                )
            }.isInstanceOf(AssertionError::class.java)
                .hasMessageContaining("JSON array at '$.items'")
                .hasMessageContaining("must contain at least one representative item")
        }

        @Test
        fun `recursive shape helper checks every actual array element`() {
            val actual = objectMapper.readTree("""{"items":[{"field":true},{"extra":true}]}""")
            val expected = objectMapper.readTree("""{"items":[{"field":true}]}""")

            assertThatThrownBy {
                assertJsonShapeMatches(
                    actual = actual,
                    expected = expected,
                    path = "$",
                    fixtureFileName = "inline-fixture.json",
                )
            }.isInstanceOf(AssertionError::class.java)
                .hasMessageContaining("JSON object key set at '$.items[1]'")
                .hasMessageContaining("extra")
                .hasMessageContaining("field")
        }

        private fun sessionCookieForUser(userId: String): Cookie {
            val issuedSession =
                authSessionService.issueSession(
                    userId = UUID.fromString(userId).toString(),
                    userAgent = "FrontendZodSchemaContractTest",
                    ipAddress = "127.0.0.1",
                )
            createdSessionTokenHashes += issuedSession.storedTokenHash
            return Cookie(AuthSessionService.COOKIE_NAME, issuedSession.rawToken)
        }

        private fun assertJsonShapeMatches(
            actualJson: String,
            fixtureFileName: String,
        ) {
            val fixtureFile = zodFixturesDir.resolve(fixtureFileName).toFile()
            check(fixtureFile.exists()) {
                "Frontend zod schema fixture file not found: ${fixtureFile.absolutePath}. " +
                    "Run `pnpm --dir front zod:export-fixtures` to generate fixtures, " +
                    "then ensure 'readmates.frontend.zod.fixtures.dir' points to " +
                    "front/tests/unit/__fixtures__/zod-schemas."
            }

            val actual: JsonNode = objectMapper.readTree(actualJson)
            val expected: JsonNode = objectMapper.readTree(fixtureFile)

            assertJsonShapeMatches(
                actual = actual,
                expected = expected,
                path = "$",
                fixtureFileName = fixtureFileName,
            )
        }

        private fun assertJsonShapeMatches(
            actual: JsonNode?,
            expected: JsonNode,
            path: String,
            fixtureFileName: String,
        ) {
            if (expected.isObject) {
                assertObjectKeysMatch(
                    actual = actual,
                    expected = expected,
                    path = path,
                    fixtureFileName = fixtureFileName,
                )
                return
            }

            if (expected.isArray) {
                assertThat(actual?.isArray)
                    .describedAs("JSON node at '$path' from '$fixtureFileName' must be an array")
                    .isTrue()

                if (!expected.isEmpty) {
                    assertThat(actual!!.isEmpty)
                        .describedAs("JSON array at '$path' from '$fixtureFileName' must contain at least one representative item")
                        .isFalse()

                    for (index in 0 until actual.size()) {
                        assertJsonShapeMatches(
                            actual = actual.get(index),
                            expected = expected.get(0),
                            path = "$path[$index]",
                            fixtureFileName = fixtureFileName,
                        )
                    }
                }
            }
        }

        private fun assertObjectKeysMatch(
            actual: JsonNode?,
            expected: JsonNode,
            path: String,
            fixtureFileName: String,
        ) {
            assertThat(actual?.isObject)
                .describedAs("JSON node at '$path' from '$fixtureFileName' must be an object")
                .isTrue()

            val actualKeys = actual!!.propertyNames().toSet()
            val expectedKeys = expected.propertyNames().toSet()

            assertThat(actualKeys)
                .describedAs(
                    "JSON object key set at '$path' from server response must match zod schema fixture '$fixtureFileName'.\n" +
                        "Keys in server response but not in zod fixture: ${actualKeys - expectedKeys}\n" +
                        "Keys in zod fixture but not in server response: ${expectedKeys - actualKeys}",
                ).isEqualTo(expectedKeys)

            expectedKeys
                .intersect(actualKeys)
                .sorted()
                .forEach { key ->
                    assertJsonShapeMatches(
                        actual = actual.get(key),
                        expected = expected.get(key),
                        path = "$path.$key",
                        fixtureFileName = fixtureFileName,
                    )
                }
        }

        private companion object {
            private const val OWNER_USER_ID = "00000000-0000-0000-0000-000000000901"
            private const val MEMBER_USER_ID = "00000000-0000-0000-0000-000000000106"

            private const val CLEANUP_CONTRACT_CURRENT_SESSION_SQL = """
                delete from long_reviews
                where session_id = '00000000-0000-0000-0000-000000000977';
                delete from one_line_reviews
                where session_id = '00000000-0000-0000-0000-000000000977';
                delete from questions
                where session_id = '00000000-0000-0000-0000-000000000977';
                delete from reading_checkins
                where session_id = '00000000-0000-0000-0000-000000000977';
                delete from session_participants
                where session_id = '00000000-0000-0000-0000-000000000977';
                delete from sessions
                where id = '00000000-0000-0000-0000-000000000977';
            """

            private const val INSERT_CONTRACT_CURRENT_SESSION_SQL = """
                insert into sessions (
                  id, club_id, number, title, book_title, book_author, book_translator, book_link,
                  session_date, start_time, end_time, location_label, question_deadline_at, state
                )
                values (
                  '00000000-0000-0000-0000-000000000977',
                  '00000000-0000-0000-0000-000000000001',
                  977, '977회차 · 계약 테스트 책', '계약 테스트 책', '계약 테스트 저자', null, null,
                  '2026-05-20', '20:00', '22:00', '온라인',
                  '2026-05-19 14:59:00.000000', 'OPEN'
                );
            """

            private const val INSERT_CONTRACT_CURRENT_SESSION_PARTICIPANTS_SQL = """
                insert into session_participants (id, club_id, session_id, membership_id, rsvp_status, attendance_status)
                select uuid(), memberships.club_id, '00000000-0000-0000-0000-000000000977', memberships.id, 'GOING', 'UNKNOWN'
                from memberships
                join users on users.id = memberships.user_id
                where users.email in ('host@example.com', 'member1@example.com', 'member5@example.com');
            """

            private const val INSERT_CONTRACT_CURRENT_SESSION_QUESTION_SQL = """
                insert into questions (id, club_id, session_id, membership_id, priority, text, draft_thought)
                select '00000000-0000-0000-0000-000000009977', memberships.club_id,
                       '00000000-0000-0000-0000-000000000977', memberships.id,
                       1, '계약 테스트 질문', '계약 테스트 초안'
                from memberships
                join users on users.id = memberships.user_id
                where users.email = 'member5@example.com';
            """

            private const val INSERT_CONTRACT_CURRENT_SESSION_CHECKIN_SQL = """
                insert into reading_checkins (id, club_id, session_id, membership_id, reading_progress)
                select '00000000-0000-0000-0000-000000009978', memberships.club_id,
                       '00000000-0000-0000-0000-000000000977', memberships.id, 72
                from memberships
                join users on users.id = memberships.user_id
                where users.email = 'member5@example.com';
            """

            private const val INSERT_CONTRACT_CURRENT_SESSION_ONE_LINE_REVIEW_SQL = """
                insert into one_line_reviews (id, club_id, session_id, membership_id, text, visibility)
                select '00000000-0000-0000-0000-000000009979', memberships.club_id,
                       '00000000-0000-0000-0000-000000000977', memberships.id,
                       '계약 테스트 한줄평', 'PRIVATE'
                from memberships
                join users on users.id = memberships.user_id
                where users.email = 'member5@example.com';
            """

            private const val INSERT_CONTRACT_CURRENT_SESSION_MY_LONG_REVIEW_SQL = """
                insert into long_reviews (id, club_id, session_id, membership_id, body, visibility)
                select '00000000-0000-0000-0000-000000009980', memberships.club_id,
                       '00000000-0000-0000-0000-000000000977', memberships.id,
                       '계약 테스트 내 서평', 'PRIVATE'
                from memberships
                join users on users.id = memberships.user_id
                where users.email = 'member5@example.com';
            """

            private const val INSERT_CONTRACT_CURRENT_SESSION_BOARD_LONG_REVIEW_SQL = """
                insert into long_reviews (id, club_id, session_id, membership_id, body, visibility)
                select '00000000-0000-0000-0000-000000009981', memberships.club_id,
                       '00000000-0000-0000-0000-000000000977', memberships.id,
                       '계약 테스트 보드 서평', 'PRIVATE'
                from memberships
                join users on users.id = memberships.user_id
                where users.email = 'member1@example.com';
            """
        }
    }
