package com.readmates.notification.application

class NotificationApplicationException(
    val error: NotificationApplicationError,
    message: String,
) : RuntimeException(message)

enum class NotificationApplicationError {
    NOTIFICATION_NOT_FOUND,
    INVALID_TEST_MAIL_EMAIL,
    TEST_MAIL_COOLDOWN,
    MANUAL_NOTIFICATION_TEMPLATE_UNAVAILABLE,
    MANUAL_NOTIFICATION_AUDIENCE_EMPTY,
    DUPLICATE_NOTIFICATION_DISPATCH,
    MANUAL_NOTIFICATION_PREVIEW_NOT_FOUND,
    MANUAL_NOTIFICATION_PREVIEW_EXPIRED,
    MANUAL_NOTIFICATION_PREVIEW_REUSED,
    MANUAL_NOTIFICATION_SELECTION_INVALID,
    MANUAL_NOTIFICATION_RECIPIENT_INVALID,
    MANUAL_NOTIFICATION_RECIPIENTS_CHANGED,
    MANUAL_NOTIFICATION_CONTENT_STALE,
    MANUAL_NOTIFICATION_STATE_INVALID,
    MEMBERSHIP_NOT_ALLOWED,
    ADMIN_NOTIFICATION_REPLAY_REASON_REQUIRED,
    ADMIN_NOTIFICATION_REPLAY_PREVIEW_EXPIRED,
    ADMIN_NOTIFICATION_REPLAY_PREVIEW_NOT_FOUND,
    ADMIN_NOTIFICATION_REPLAY_SELECTION_MISMATCH,
}
