apiVersion: 1

datasources:
  - name: ReadMates Local Tempo
    uid: readmates-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      httpMethod: GET
