create table notification_outbox (
  id char(36) not null,
  club_id char(36) not null,
  event_type varchar(60) not null,
  aggregate_type varchar(60) not null,
  aggregate_id char(36) not null,
  recipient_membership_id char(36),
  recipient_email varchar(320) not null,
  recipient_display_name varchar(100),
  subject varchar(200) not null,
  body_text text not null,
  deep_link_path varchar(500) not null,
  status varchar(20) not null default 'PENDING',
  attempt_count int not null default 0,
  next_attempt_at datetime(6) not null default (utc_timestamp(6)),
  locked_at datetime(6),
  sent_at datetime(6),
  last_error varchar(500),
  dedupe_key varchar(180) not null,
  created_at datetime(6) not null default (utc_timestamp(6)),
  updated_at datetime(6) not null default current_timestamp(6) on update current_timestamp(6),
  primary key (id),
  unique key notification_outbox_dedupe_key_uk (dedupe_key),
  key notification_outbox_status_next_idx (status, next_attempt_at, created_at),
  key notification_outbox_club_created_idx (club_id, created_at),
  constraint notification_outbox_club_fk foreign key (club_id) references clubs(id),
  constraint notification_outbox_recipient_membership_fk foreign key (recipient_membership_id, club_id) references memberships(id, club_id),
  constraint notification_outbox_status_check check (status in ('PENDING', 'SENDING', 'SENT', 'FAILED', 'DEAD')),
  constraint notification_outbox_attempt_count_check check (attempt_count >= 0),
  constraint notification_outbox_email_check check (length(trim(recipient_email)) > 0),
  constraint notification_outbox_subject_check check (length(trim(subject)) > 0),
  constraint notification_outbox_body_check check (length(trim(body_text)) > 0),
  constraint notification_outbox_deep_link_path_check check (deep_link_path like '/%'),
  constraint notification_outbox_dedupe_key_check check (length(trim(dedupe_key)) > 0)
);
