create table notification_event_outbox (
  id char(36) not null,
  club_id char(36) not null,
  event_type varchar(60) not null,
  aggregate_type varchar(60) not null,
  aggregate_id char(36) not null,
  payload_json json not null,
  status varchar(20) not null default 'PENDING',
  kafka_topic varchar(180) not null default 'readmates.notification.events.v1',
  kafka_key varchar(180) not null,
  attempt_count int not null default 0,
  next_attempt_at datetime(6) not null default (utc_timestamp(6)),
  locked_at datetime(6),
  published_at datetime(6),
  last_error varchar(500),
  dedupe_key varchar(220) not null,
  created_at datetime(6) not null default (utc_timestamp(6)),
  updated_at datetime(6) not null default current_timestamp(6) on update current_timestamp(6),
  primary key (id),
  unique key notification_event_outbox_dedupe_key_uk (dedupe_key),
  unique key notification_event_outbox_id_club_uk (id, club_id),
  key notification_event_outbox_status_next_idx (status, next_attempt_at, created_at),
  key notification_event_outbox_club_status_idx (club_id, status, updated_at, created_at),
  constraint notification_event_outbox_club_fk foreign key (club_id) references clubs(id),
  constraint notification_event_outbox_status_check check (status in ('PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'DEAD')),
  constraint notification_event_outbox_attempt_count_check check (attempt_count >= 0),
  constraint notification_event_outbox_dedupe_key_check check (length(trim(dedupe_key)) > 0),
  constraint notification_event_outbox_kafka_topic_check check (length(trim(kafka_topic)) > 0),
  constraint notification_event_outbox_kafka_key_check check (length(trim(kafka_key)) > 0)
) default character set utf8mb4 collate utf8mb4_0900_ai_ci;

create table notification_deliveries (
  id char(36) not null,
  event_id char(36) not null,
  club_id char(36) not null,
  recipient_membership_id char(36) not null,
  channel varchar(20) not null,
  status varchar(20) not null default 'PENDING',
  dedupe_key varchar(260) not null,
  attempt_count int not null default 0,
  next_attempt_at datetime(6) not null default (utc_timestamp(6)),
  locked_at datetime(6),
  sent_at datetime(6),
  skip_reason varchar(120),
  last_error varchar(500),
  created_at datetime(6) not null default (utc_timestamp(6)),
  updated_at datetime(6) not null default current_timestamp(6) on update current_timestamp(6),
  primary key (id),
  unique key notification_deliveries_dedupe_key_uk (dedupe_key),
  unique key notification_deliveries_id_context_uk (id, event_id, club_id, recipient_membership_id),
  key notification_deliveries_event_idx (event_id, channel, status),
  key notification_deliveries_event_club_idx (event_id, club_id),
  key notification_deliveries_club_status_idx (club_id, status, updated_at, created_at),
  key notification_deliveries_retry_idx (status, next_attempt_at, created_at),
  constraint notification_deliveries_event_club_fk foreign key (event_id, club_id) references notification_event_outbox(id, club_id),
  constraint notification_deliveries_recipient_fk foreign key (recipient_membership_id, club_id) references memberships(id, club_id),
  constraint notification_deliveries_channel_check check (channel in ('EMAIL', 'IN_APP')),
  constraint notification_deliveries_status_check check (status in ('PENDING', 'SENDING', 'SENT', 'FAILED', 'DEAD', 'SKIPPED')),
  constraint notification_deliveries_attempt_count_check check (attempt_count >= 0),
  constraint notification_deliveries_dedupe_key_check check (length(trim(dedupe_key)) > 0)
) default character set utf8mb4 collate utf8mb4_0900_ai_ci;

create table member_notifications (
  id char(36) not null,
  event_id char(36) not null,
  delivery_id char(36) not null,
  club_id char(36) not null,
  recipient_membership_id char(36) not null,
  event_type varchar(60) not null,
  title varchar(160) not null,
  body varchar(500) not null,
  deep_link_path varchar(500) not null,
  read_at datetime(6),
  created_at datetime(6) not null default (utc_timestamp(6)),
  primary key (id),
  unique key member_notifications_delivery_uk (delivery_id),
  unique key member_notifications_event_recipient_uk (event_id, club_id, recipient_membership_id),
  key member_notifications_delivery_context_idx (delivery_id, event_id, club_id, recipient_membership_id),
  key member_notifications_recipient_read_created_idx (recipient_membership_id, read_at, created_at),
  key member_notifications_recipient_created_idx (recipient_membership_id, created_at),
  key member_notifications_club_created_idx (club_id, created_at),
  constraint member_notifications_event_club_fk foreign key (event_id, club_id) references notification_event_outbox(id, club_id),
  constraint member_notifications_delivery_context_fk
    foreign key (delivery_id, event_id, club_id, recipient_membership_id)
    references notification_deliveries(id, event_id, club_id, recipient_membership_id),
  constraint member_notifications_recipient_fk foreign key (recipient_membership_id, club_id) references memberships(id, club_id),
  constraint member_notifications_title_check check (length(trim(title)) > 0),
  constraint member_notifications_body_check check (length(trim(body)) > 0),
  constraint member_notifications_deep_link_path_check check (deep_link_path like '/%')
) default character set utf8mb4 collate utf8mb4_0900_ai_ci;
