CREATE TABLE ai_generation_audit_log (
  id                    BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_id                CHAR(36)     NOT NULL,
  session_id            CHAR(36)     NOT NULL,
  club_id               CHAR(36)     NOT NULL,
  host_user_id          CHAR(36)     NOT NULL,
  kind                  VARCHAR(32)  NOT NULL,
  item                  VARCHAR(32)  NULL,
  provider              VARCHAR(16)  NOT NULL,
  model                 VARCHAR(64)  NOT NULL,
  transcript_sha256     CHAR(64)     NULL,
  input_tokens          INT          NOT NULL DEFAULT 0,
  cached_input_tokens   INT          NOT NULL DEFAULT 0,
  output_tokens         INT          NOT NULL DEFAULT 0,
  cost_estimate_usd     DECIMAL(8,4) NOT NULL DEFAULT 0,
  status                VARCHAR(16)  NOT NULL,
  error_code            VARCHAR(64)  NULL,
  error_message         VARCHAR(512) NULL,
  latency_ms            INT          NOT NULL DEFAULT 0,
  created_at            DATETIME(6)  NOT NULL,
  INDEX idx_aigen_audit_session (session_id, created_at),
  INDEX idx_aigen_audit_club    (club_id,    created_at),
  INDEX idx_aigen_audit_host    (host_user_id, created_at)
);
